2020-08-14T15:02:17.6869262+05:30 80000007-0000-fd00-b63f-84710c7967bb [INF] Request starting HTTP/2.0 GET https://localhost:44383/api/values   (ca22a1cb)
2020-08-14T15:02:18.2899946+05:30 80000007-0000-fd00-b63f-84710c7967bb [INF] Route matched with "{action = \"SaveOnlineOrder\", controller = \"Values\"}". Executing controller action with signature "Void SaveOnlineOrder(Newtonsoft.Json.Linq.JObject)" on controller "Biz1PosApi.Controllers.ValuesController" ("Biz1PosApi"). (122b2fdf)
2020-08-14T15:02:18.5375064+05:30 80000007-0000-fd00-b63f-84710c7967bb [INF] Executed action "Biz1PosApi.Controllers.ValuesController.SaveOnlineOrder (Biz1PosApi)" in 241.6128ms (afa2e885)
2020-08-14T15:02:18.5870812+05:30 80000007-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentNullException: Value cannot be null.
Parameter name: modelMetadata
   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.EnterNestedScope(ModelMetadata modelMetadata, String fieldName, String modelName, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinder`2.TryBindStrongModel[TModel](ModelBindingContext bindingContext, IModelBinder binder, String propertyName, String propertyModelName)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinder`2.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.BindComplexCollectionFromIndexes(ModelBindingContext bindingContext, IEnumerable`1 indexNames)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinder`2.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-14T15:02:18.6715715+05:30 80000007-0000-fd00-b63f-84710c7967bb [INF] Request finished in 986.411ms 500 text/html; charset=utf-8 (791a596a)
2020-08-14T15:03:13.5669769+05:30 8000000f-0000-fe00-b63f-84710c7967bb [INF] Request starting HTTP/2.0 GET https://localhost:44383/api/values   (ca22a1cb)
2020-08-14T15:03:14.1350333+05:30 8000000f-0000-fe00-b63f-84710c7967bb [INF] Route matched with "{action = \"SaveOnlineOrder\", controller = \"Values\"}". Executing controller action with signature "Void SaveOnlineOrder(Newtonsoft.Json.Linq.JObject)" on controller "Biz1PosApi.Controllers.ValuesController" ("Biz1PosApi"). (122b2fdf)
2020-08-14T15:03:14.3708518+05:30 8000000f-0000-fe00-b63f-84710c7967bb [INF] Executed action "Biz1PosApi.Controllers.ValuesController.SaveOnlineOrder (Biz1PosApi)" in 229.8762ms (afa2e885)
2020-08-14T15:03:14.4158890+05:30 8000000f-0000-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentNullException: Value cannot be null.
Parameter name: modelMetadata
   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.EnterNestedScope(ModelMetadata modelMetadata, String fieldName, String modelName, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinder`2.TryBindStrongModel[TModel](ModelBindingContext bindingContext, IModelBinder binder, String propertyName, String propertyModelName)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinder`2.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.BindComplexCollectionFromIndexes(ModelBindingContext bindingContext, IEnumerable`1 indexNames)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinder`2.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-14T15:03:14.4801522+05:30 8000000f-0000-fe00-b63f-84710c7967bb [INF] Request finished in 919.1304ms 500 text/html; charset=utf-8 (791a596a)
2020-08-14T15:03:36.2459078+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Request starting HTTP/2.0 GET https://localhost:44383/api/Values/errorlogging   (ca22a1cb)
2020-08-14T15:03:36.2588904+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Route matched with "{action = \"errorlogging\", controller = \"Values\"}". Executing controller action with signature "System.String errorlogging()" on controller "Biz1PosApi.Controllers.ValuesController" ("Biz1PosApi"). (122b2fdf)
2020-08-14T15:03:36.2712590+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Executing action method "Biz1PosApi.Controllers.ValuesController.errorlogging (Biz1PosApi)" - Validation state: Valid (dad538d7)
2020-08-14T15:03:36.2737722+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Hello, world! (f83bcf75)
2020-08-14T15:03:36.2851227+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Executed action method "Biz1PosApi.Controllers.ValuesController.errorlogging (Biz1PosApi)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 7.7019ms. (50a9e262)
2020-08-14T15:03:36.2963264+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Executing ObjectResult, writing value of type '"System.String"'. (8a1b66c8)
2020-08-14T15:03:36.2993531+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Executed action "Biz1PosApi.Controllers.ValuesController.errorlogging (Biz1PosApi)" in 38.6912ms (afa2e885)
2020-08-14T15:03:36.3010555+05:30 80000011-0000-fe00-b63f-84710c7967bb [INF] Request finished in 59.9277ms 200 text/plain; charset=utf-8 (791a596a)
